## 学习手写数字分类

In [1]:
import tensorflow as tf

#### 将手写数字的灰度图像（28 像素×28 像素）划分到10 个类别中（0~9），使用MNIST 数据集

### 加载 Keras中的MNIST 数据集

In [43]:
from keras.datasets import mnist
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()

In [44]:
print('训练图像 train_images :',train_images.shape)
print("训练标签 train_labels 前5行:",train_labels[0:5])
print("*******************************************")
print('测试图像 test_images:',test_images.shape)
print("测试标签 test_labels 前5行:",test_labels[0:5])

训练图像 train_images : (60000, 28, 28)
训练标签 train_labels 前5行: [5 0 4 1 9]
*******************************************
测试图像 test_images: (10000, 28, 28)
测试标签 test_labels 前5行: [7 2 1 0 4]


In [46]:
import pandas as pd
# 统计列表中元素出现的次数
result=pd.value_counts(train_labels)
print(result)

1    6742
7    6265
3    6131
2    5958
9    5949
0    5923
6    5918
8    5851
4    5842
5    5421
dtype: int64


### 网络架构

In [51]:
from keras import models
from keras import layers
# 神经网络的核心组件是层(layer)，它是一种数据处理模块（看做为数据过滤器），实现数据蒸馏

network=models.Sequential()
network.add(layers.Dense(512,activation='relu',input_shape=(28*28,)))
# 密集连接(也叫全连接)的神经层
network.add(layers.Dense(10,activation='softmax'))
# 最后一层，一个10路的softmax层，将返回一个由10个概率值(总和为1)组成的数组

### 编译步骤

In [52]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

#### 要想训练网络，选择编译(compile)步骤的三个参数

1.优化器 optimizer:基于训练数据和损失函数来更新网络的机制
    
2.损失函数loss function:网络如何衡量在训练数据上的性能
    
3.在训练和测试过程中需要监控的指标 metrics:本例只关心精度

### 准备图像数据

In [53]:
train_images=train_images.reshape((60000,28*28))
train_images=train_images.astype('float32')/255

test_images=test_images.reshape((10000,28*28))
test_images=test_images.astype('float32')/255

### 准备标签

In [54]:
from keras.utils import to_categorical
train_labels=to_categorical(train_labels) 
test_labels=to_categorical(test_labels)

In [55]:
print('独热编码后标签：',train_labels[0])

独热编码后标签： [[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


In [56]:
network.fit(train_images,train_labels,epochs=5,batch_size=128)

ValueError: Error when checking target: expected dense_6 to have 2 dimensions, but got array with shape (60000, 10, 2)

#### to_categorical将类别向量转换为二进制（只有0和1）的矩阵类型表示。其表现为将原有的类别向量转换为独热编码的形式

In [39]:
from keras.utils.np_utils import *
#类别向量定义
b = [0,1,2,3,4,5,6,7,8]
#调用to_categorical将b按照9个类别来进行转换
b = to_categorical(b, 9)
print(b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
